### ISSUE TITLE
Is it possible to collect extended tweets with stream?

### ISSUE THREAD

**Issue by vigaeatery** [geduldig/TwitterAPI#122]
Is it possible to collect the un-truncated text for tweets that require extended mode with this library? I think some libraries use tweet_mode='extended' and then the payload contains a "full_text" field. 

Thank you very much for the help.

**Comment by albertboston** [comment]
You are a legend. Thank you, this works perfectly.
On a side note are you aware of a method to exclude certain users?
My particular user case is to try to filter bot-users by their usernames from the collected tweets
since they are the overwhelming majority for the hashtags I am tracking. 

Thanks so much again.
