### ISSUE TITLE
Conversation Tree Issue

### ISSUE THREAD

**Issue by johanneskaiser894** [geduldig/TwitterAPI#161]
<img width="511" alt="Bildschirmfoto 2021-01-25 um 22 52 20" src="https://user-images.githubusercontent.com/57792245/105771097-573c4980-5f60-11eb-9822-7ebf93e8991c.png">
<img width="449" alt="Bildschirmfoto 2021-01-25 um 22 53 29" src="https://user-images.githubusercontent.com/57792245/105771100-586d7680-5f60-11eb-892f-e3d71cf03c52.png">
<img width="979" alt="Bildschirmfoto 2021-01-25 um 22 52 05" src="https://user-images.githubusercontent.com/57792245/105771101-59060d00-5f60-11eb-8ce8-f49b64224c99.png">

Hi geduldig, thanks for your great work! Unfortunately I found a bug with the Python Conversation Tree. Strangely, there are posts in between that are not in the right place, such as here in the example. Do you have any idea how to fix this? Many greetings

**Comment by geduldig** [comment]
Hi - I don't quite follow your example output as to exactly what is out of order. However, if that is the issue it is likely caused by my neglecting to order the conversation chronologically before assembling the conversation tree. I should be able to make this fix in the next couple of days. When I do, you can retry. I'll post here when you can get my updated code. Thanks!

**Comment by geduldig** [comment]
The conversation tree example, I think, now works correctly

https://github.com/geduldig/TwitterAPI/blob/master/examples/v2/conversation_tree.py

The problem was the tree used user ID's to link each tweet to it's reply-to post. Now tweets are linked by the tweet id. The reply-to tweet ID's are contained in the `referenced_tweets` property of each tweet. Let me know if this fixes the issue you found.

**Comment by johanneskaiser894** [comment]
Thanks for that, I tried that for several examples and it seems to work perfectly now.
