### ISSUE TITLE
Add support for OAuth2 authentication with access_tokens

### ISSUE THREAD

**Issue by codewithbas** [geduldig/TwitterAPI#220]
This is needed for some API endpoints, see for example #219

**Comment by v1nc3nt27** [comment]
I am a bit confused about this, could you perhaps elaborate why this is needed because oatuh2 was already integrated: http://geduldig.github.io/TwitterAPI/authentication.html. Or was this only usable in twitter API v1.1 and in v2 we need bearer token and this is why you added this option? Would be great if you could clarify this for me. Thanks a lot!
