### ISSUE TITLE
Getting tweets from a location

### ISSUE THREAD

**Issue by maxwelldonkoh** [geduldig/TwitterAPI#57]
Does this only support tweets from NYC? Because when I try other latitudes and longitudes, I get a request failed error

**Comment by geduldig** [comment]
You might have a better time if you read the [docs](https://dev.twitter.com/overview/documentation) for the endpoint you are using. Or, if you prefer, post the request the request you are making, I probably can tell you why you are getting this error.

**Comment by maxwelldonkoh** [comment]
'statuses/filter', {'locations':'-74,40,-73,41'})'. I got this from the main Github page for the API. And replaced -74,40, -73,41 with latitudes that are not for New York. Using an instance of TwitterRestPager as well

**Comment by geduldig** [comment]
For me to help you, you will have to post the request that failed, not the request that worked. If you can post the exact line of code for the request that would be even better.

**Comment by maxwelldonkoh** [comment]
r = TwitterRestPager(api, 'statuses/filter', {'locations':'-71,42,-72,43'}). 

This is failing and a lot of other examples I've tried also fail

**Comment by geduldig** [comment]
The doc for `statuses/filter` is [here](https://dev.twitter.com/streaming/reference/post/statuses/filter). In there, there's a [link](https://dev.twitter.com/streaming/overview/request-parameters#locations) that explains the `locations` parameter. 

If you read that you will see that those four numbers are longitudinal/latitudinal pairs that describe the bounding box of your location. Twitter interprets the first pair as the southwest corner and the second pair and the northeast corner. Your first pair has a longitude of -71, and your second pair has a longitude of -72. This is not valid because -71 is *east* of -72.  Just switch these numbers and it will work.

HTH

**Comment by maxwelldonkoh** [comment]
It helped! Thanks!
