### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f319'

### ISSUE THREAD

**Issue by crimsonbinome22** [geduldig/TwitterAPI#65]
When trying to use the streaming example here:
https://github.com/geduldig/TwitterAPI/blob/master/examples/stream_tweets.py

I get following error: 
```
Traceback (most recent call last):
  File "TWC_Scraper.py", line 21, in <module>
    print(item['text'] if 'text' in item else item)
  File "C:\Python34\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f319' in posit
ion 12: character maps to <undefined>
```
Sometimes it works and I get a few tweets, but it'll fail again after a few seconds, sometimes encountering other characters like \U0001f355 or something else.

Guessing this isn't something to do with module, but maybe fontset on my laptop but I couldn't make sense of stack overflow examples. Any suggestions on how to circumvent?

**Comment by geduldig** [comment]
You must be running this on a Windows console. The problem is the Windows console font does not support unicode. There are a couple of things you can do.

The simplest is the following.
```
    try:
        # python 3
        sys.stdout = codecs.getwriter('utf8')(sys.stdout.buffer)
    except:
        # python 2
        sys.stdout = codecs.getwriter('utf8')(sys.stdout)
```
With this code you will get square boxes substituted for unicode characters, but at least your code won't crash.

Look at [examples\cli.py](https://github.com/geduldig/TwitterAPI/blob/master/examples/cli.py) for a better solution. Basically, add the following to your code.
```
    if sys.platform == "win32":
        from Unicode_win32 import stdout
        sys.stdout = stdout
```
This also prints out square boxes, but some common unicode characters, like accents, umlauts, etc., get printed correctly.

Neither solution will print out emoji and other similar unicode characters -- unless you are on a Mac or some other type of console that supports unicode.

**Comment by crimsonbinome22** [comment]
Good spot, should've thought of that. Your suggestion
```sys.stdout = codecs.getwriter('utf8')(sys.stdout.buffer)```
works a charm

**Comment by Amal80** [comment]
in which file did you add this line?
sys.stdout = codecs.getwriter('utf8')(sys.stdout.buffer)

**Comment by geduldig** [comment]
Any file that prints to stdout.

**Comment by ztavlas** [comment]
if you are working on windows console, then you can solve your codec problem by adding these two lines to your code :

```
import win_unicode_console
win_unicode_console.enable()

```
