### ISSUE TITLE
Stream stalled

### ISSUE THREAD

**Issue by actioncrypto** [geduldig/TwitterAPI#70]
Hello there,

So - very sporadically, and randomly, this script's thread may get a crash that seems to be unrecoverable. The error is pasted below:

    WARNING:root:<type 'str'> Twitter stream stalled
    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/Users/myuser/.pyenv/versions/2.7.9/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/Users/myuser/.pyenv/versions/2.7.9/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "python_file_in_question.py", line 57, in streamTweet
        for item in r:
      File "/Users/myuser/.pyenv/versions/2.7.9/lib/python2.7/site-packages/TwitterAPI/TwitterAPI.py", line 288, in __iter__
        for item in self._iter_stream():
      File "/Users/myuser/.pyenv/versions/2.7.9/lib/python2.7/site-packages/TwitterAPI/TwitterAPI.py", line 263, in _iter_stream
        raise TwitterConnectionError('Twitter stream stalled')
    TwitterConnectionError: Twitter stream stalled

I tried to add a try/except and re-log in, but it did not fix my issue. This is the relevant part from the head of streamTweet:

    def streamTweet(api):
	    try:
		    r = api.request('user')
        except Exception as e:
		    logger.warning('Twitter ERROR:: %s', e)
		    api = logOnTwitter()
		    r = api.request('user')
 	    for item in r:
		    if 'direct_message' in item:
                pass # doing other stuff here

Also, it is not hitting the log file or console prints, so it leads me to believe the script dies AFTER we have `r = api.request('user')` success.  Not sure how to fix this situation since it's not hitting the try/except.... any ideas what is up?

**Comment by geduldig** [comment]
Hi,
These "hangs" are caused by stalls in the stream. You can read about them [here](https://dev.twitter.com/streaming/overview/connecting). When they occur, Twitter suggests reconnecting. 

The last line in your error output is:
`
TwitterConnectionError: Twitter stream stalled
`
This exception indicates that you should reconnect.

I wrote a short document [here](http://geduldig.github.io/TwitterAPI/faulttolerance.html) which shows how to handle `TwitterConnectionError` and `TwitterRequestError` in order to keep your stream running indefinitely. There are a few (rare) cases you need to take of.
