### ISSUE TITLE
Issue with the new text formatting of Tweets

### ISSUE THREAD

**Issue by fraba** [geduldig/TwitterAPI#79]
I noticed that few tweets get truncated. It might depend on the change in the limit of characters when links and handles are involved?

For example, this tweet (786178752753573889), which includes the link to a picture, gets truncated 

> Se il #PD usa argomenti del Pdl (ora @forza_italia) per sostenere #Si al #referendumcostituzionale siamo proprio al… https://t.co/GvLoWesKYP

while here as it appears on [Twitter.com](https://twitter.com/claudriso/status/786178752753573889)

> Se il #PD usa argomenti del Pdl (ora @forza_italia) per sostenere #Si al #referendumcostituzionale siamo proprio all'involuzione
#IoVotoNO

**Comment by geduldig** [comment]
When you search for tweets on Twitter.com you are not using the public Twitter API. So, don't expect to see the same results. If you are seeing truncation it is not because this library is limiting the tweet. What you see is what is returned by Twitter via their API. 

Twitter has [announced](https://dev.twitter.com/overview/api/upcoming-changes-to-tweets) changes to their API which will allow for getting the untruncated tweet text. You will just need to send the appropriate parameters.
